first commit
yoshibuchi/chat-space pull request #1
Opened 2019-05-20 10:50 UTC by yoshibuchi

#WHAT
制約をつけるため
#WHY
安全なテーブルを設計するため

2019-05-20 12:44 UTC, kuroko918 requested changes
.

2019-05-20 12:44 UTC, kuroko918 commented on README.md
> +has_many :group
外部キーカラムがあるのに、has_manyというのはおかしいですね！
belongs_toですね！

2019-05-20 12:44 UTC, kuroko918 commented on README.md
> +has_many :group
外部キーカラムがあるのに、has_manyというのはおかしいですね！
belongs_toですね！

2019-05-21 02:00 UTC, shingoteshima commented on README.md
> +has_many :message
messagesと複数形にしましょう。

2019-05-21 02:00 UTC, shingoteshima commented on README.md
> +|name|string|null: false|
nameにindex貼りましょう。

2019-05-26 15:18 UTC, merged

2019-05-27 02:07 UTC, TOMARUMARU commented
LGTMが出るまでmergeはしないでください。
今回は良さそうなので次に進んでいただいて大丈夫です